### ISSUE TITLE
GenesisProtocol: Updating proposal status after the defined time period

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc.js#169]
Since the blockchain doesn't update unless a function is invoked, proposal details may be out-of-date when doing `genesisProtocol.getProposal(..)` (e.g. the defined voting time period has passed and no one invoked `vote`, `stake` or `execute`). 
We can check if there should be a state change by calling `genesisProtocol.execute.call(..)`, and then either indicate somehow that the information is out-of-date, or actually perform the state change on the blockchain by calling `genesisProtocol.sendTransaction(..)` before retrieving the info about the proposal.

**Comment by dev-matan-tsuberi** [comment]
me and @dkent600 reached the conclusion that we should have a function `syncVote`/`needToExecute` that only checks locally if the proposal needs to be executed by calling `gp.exeute.call(..)`. Then we'll have in a button "Execute" in the alchemy UI that lets the user actually `gp.execute(..)` the proposal.

opinions? @tibetsprague @leviadam

**Comment by dkent600** [comment]
I was thinking that the `syncVote` would also call `execute` if needed.  Or, that could be done optionally based on an input parameter.

**Comment by tibetsprague** [comment]
so who will pay the gas to execute then? its a bit weird

**Comment by tibetsprague** [comment]
I guess the beneficiary would want to

**Comment by dkent600** [comment]
> so who will pay the gas to execute then? its a bit weird

"Weird" because one is paying for a transaction simply to find out the status of an order?

Fundamentally I think in this we are working around a flaw in Arc's GenesisProtocol design. The weirdness is a consequence, proceeding from the potential for the vote to enter into this also-weird state of limbo.  (Is it in a state of both executed and not executed until we check?  ;-) )

This begs the question of whether it ought to be addressed somehow in Arc itself.

I'm sure this is blasphemy, but one solution could be to have a daemon running somewhere that "pings" proposals on behalf of every DAO to ensure that proposals change state when they should.

**Comment by dkent600** [comment]
> it's just the way blockchain works 

Yeah, but is it the way a DAO should work?

**Comment by dev-matan-tsuberi** [comment]
@dkent600 The blockchain does not update unless you poke it, so no, there's no other option except to poke it.

**Comment by dev-matan-tsuberi** [comment]
split issue to: https://github.com/daostack/alchemy/issues/50, https://github.com/daostack/arc.js/issues/177
