### ISSUE TITLE
Cannot read property 'address' of null

### ISSUE THREAD

**Issue by goodstemy** [daostack/arc.js#224]
I try to create my own simple DAO with arc.js (https://daostack.github.io/arc.js/Daos/) but I getting an error: `Cannot read property 'address' of null`.

Code:
```
import { InitializeArcJs, DAO } from "@daostack/arc.js";

(async () => {
	await InitializeArcJs({
	    filter: {
	      "ContributionReward": true,
	      "DaoCreator": true,
	      "GenesisProtocol": true,
	    },
	    "useNetworkDefaultsFor": "ganache"
	  });

	const newDao = await DAO.new({
    name: "My New DAO",
    tokenName: "My new Token",
    tokenSymbol: "MNT"
  });
})();
```

**Comment by dkent600** [comment]
@goodstemy 

Do you see any additional error messages in the javascript console?  (Make sure the LogLevel is set to at least `LogLevel.debug`.  The default is `LogLevel.info | LogLevel.debug`.)

Have you migrated the contracts to ganache?

Does it make any difference if you leave out the filter?

(BTW, you don't need `"useNetworkDefaultsFor": "ganache"` since ganache is the default.)

**Comment by goodstemy** [comment]
I enable debug mode. Now I getting this: 

<img width="738" alt="2018-05-19 19 35 59" src="https://user-images.githubusercontent.com/8494692/40271320-f56198fc-5b9b-11e8-9196-0a0933a40f88.png">

**Comment by dkent600** [comment]
@goodstemy 

It works if you include `AbsoluteVote: true,` in your filter.  `AbsoluteVote` is the default voting machine and must be loaded,

If you wish to use `GenesisProtocol` instead, then see [this page in the docs](https://daostack.github.io/arc.js/Daos/#creating-a-new-dao-overriding-the-default-voting-machine).

**Comment by dkent600** [comment]
BTW, I told you wrong above, the default log leveI is `LogLevel.info | LogLevel.error`, and I meant to ask you to set your logging level to:  `LogLevel.info | LogLevel.error`.
